version: '3.7'

services:
  backend:
    build:
      context: ./Closure_Project
      dockerfile: Dockerfile.prod
    command: gunicorn Closure_Project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/backend/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend



volumes:
  postgres_data:
  static_volume:
