version: '3.7'

services:
  backend:
    build: ./Closure_Project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Closure_Project:/usr/src/Clousre_Project/
    ports:
      - 8000:8000
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


volumes:
  postgres_data:
