# Generated by Django 3.2.4 on 2021-06-15 15:22

from django.db import migrations
from pathlib import Path
import sys 

REST_API_FOLDER = Path(__file__).parent.parent
CLOSURE_PROJECT_FOLDER = REST_API_FOLDER.parent
PARSER_FOLDER = CLOSURE_PROJECT_FOLDER / "Parser"


def import_parsed_data(apps, schema_editor):
    if not PARSER_FOLDER.exists():
        raise ValueError("Parser folder missing")
    sys.path.append(str(PARSER_FOLDER))
    from OfflineParser import load_from_internet
    load_from_internet()
    
class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_parsed_data)
    ]
