# Generated by Django 3.2.4 on 2021-06-15 15:22

from django.db import migrations


from rest_api.huji_loader import load_from_zip, load_from_internet


def import_parsed_data(apps, schema_editor):
    load_from_internet()


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_parsed_data)
    ]
