# Generated by Django 3.2.4 on 2021-06-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_create_superuser'),
        ('rest_api', '0003_populate_db'),
    ]

    operations = [
    ]
