# Generated by Django 3.2.4 on 2021-06-28 23:56

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_populate_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='index_in_track_year',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='required_course_count',
            field=models.IntegerField(null=True, validators=[rest_api.models._validate_non_negative_number_or_null]),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='required_points',
            field=models.IntegerField(null=True, validators=[rest_api.models._validate_non_negative_number_or_null]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_additional_hug',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_choice',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_complementary',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_corner_stones',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_from_list',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_minor',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='points_must',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(validators=[rest_api.models._validate_non_negative_number]),
        ),
    ]
