export default [
        {
          pk: 5837,
          course_id: 67315,
          name: "סדנת תכנות בשפות C ו- ++C",
          semester: 1,
          year: 2,
          points: 4,
          type: 1,
        },
        {
          pk: 7208,
          course_id: 80131,
          name: "חשבון אינפיניטסימלי (1)",
          semester: 1,
          year: 1,
          points: 7,
          type: 1,
        },
        {
          pk: 7209,
          course_id: 80132,
          name: "חשבון אינפיניטסימלי (2)",
          semester: 2,
          year: 1,
          points: 7,
          type: 1,
        },
        {
          pk: 7211,
          course_id: 80134,
          name: "אלגברה ליניארית (1)",
          semester: 1,
          year: 1,
          points: 6,
          type: 1,
        },
        {
          pk: 7212,
          course_id: 80135,
          name: "אלגברה ליניארית (2)",
          semester: 2,
          year: 1,
          points: 6,
          type: 1,
        },
        {
          pk: 7220,
          course_id: 80181,
          name: "מתמטיקה דיסקרטית",
          semester: 1,
          year: 1,
          points: 5,
          type: 1,
        },
        {
          pk: 5844,
          course_id: 67392,
          name: "מבוא לקריפטוגרפיה ואבטחת תוכנה",
          semester: 2,
          year: 2,
          points: 4,
          type: 2,
        },
        {
          pk: 5854,
          course_id: 67506,
          name: "מסדי נתונים",
          semester: 1,
          year: 3,
          points: 5,
          type: 2,
        },
        {
          pk: 5888,
          course_id: 67609,
          name: "גרפיקה ממוחשבת",
          semester: 1,
          year: 3,
          points: 5,
          type: 3,
        },
        {
          pk: 5951,
          course_id: 67829,
          name: "עיבוד ספרתי של תמונות",
          semester: "1",
          year: 3,
          points: 4,
          type: 2,
        },
        {
          pk: 5960,
          course_id: 67842,
          name: "מבוא לבינה מלאכותית",
          semester: "2",
          year: 3,
          points: 5,
          type: 2,
        },
]