export default [
    {
        course_id: 1,
        name: "חשבון אינפיניטסימלי 1",
        points: 7,
        year: 1,
        semester: 1,
    },
    {
        course_id: 2,
        name: "מבוא למדעי המחשב",
        points: 7,
        year: 1,
        semester: 1,
    },
    {
        course_id: 3,
        name: "אלגברה ליניארית 1",
        points: 6,
        year: 1,
        semester: 1,
    },
    {
        course_id: 4,
        name: "מתמטיקה דיסקרטית",
        points: 5,
        year: 1,
        semester: 1,
    },
    {
        course_id: 5,
        name: "חשבון אינפיניטסימלי 2",
        points: 7,
        year: 1,
        semester: 2,
    },
    {
        course_id: 6,
        name: "C / C++",
        points: 4,
        year: 1,
        semester: 2,
    },
    {
        course_id: 7,
        name: "אלגברה ליניארית 2",
        points: 6,
        year: 1,
        semester: 2,
    },
    {
        course_id: 8,
        name: "מבני נתונים",
        points: 4,
        year: 1,
        semester: 2,
    },
    {
        course_id: 9,
        name: "אבן פינה קיקיונית כלשהי",
        points: 2,
        year: 1,
        semester: 2,
    },
]